### ISSUE TITLE
With nvimfs installed, I have {often,always} problems to start nvim twice

### ISSUE THREAD

**Issue by mcepl** [fmoralesc/nvimfs#5]
With nvimfs installed, I cannot run nvim twice (in different tabs of gnome-terminal, for example). I am not sure whether it is 100% reproducible or I got only my system to the state where it happens all the time, but it makes use of the plugin quite problematic. When the plugin has been removed, problems disappeared (so far).

When the second instance of nvim is run, it completely freezes on startup. There is absolutely nothing on the screen and nvim doesn't react to pressing any key I could come up with (I tried ``Ctrl-c``, ``Ctrl-l``, ``Esc``, and randomly banging to keyboard with whatever came to my mind).

``gdb --pid=$(pidof nvim)`` shows with ``t a a bt`` this:

```
matej@mitmanek: ~$ gdb --pid=$(pidof nvim)
GNU gdb (GDB) Red Hat Enterprise Linux 8.0-17.1.scylladb.1.el7.centos
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 6746
[New LWP 6755]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
38		cmpq $-4095, %rax	/* Check %rax for error.  */
(gdb) t a a bt

Thread 2 (Thread 0x7fae55bff700 (LWP 6755)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007fae5f11ee1a in uv__epoll_wait (epfd=<optimized out>, 
    events=events@entry=0x7fae55bfb790, nevents=nevents@entry=1024, 
    timeout=timeout@entry=-1) at src/unix/linux-syscalls.c:321
#2  0x00007fae5f11d14f in uv__io_poll (loop=loop@entry=0x7fae55bfe890, timeout=-1)
    at src/unix/linux-core.c:271
#3  0x00007fae5f10edb8 in uv_run (loop=loop@entry=0x7fae55bfe890, mode=UV_RUN_ONCE)
    at src/unix/core.c:352
#4  0x00000000004a0827 in loop_poll_events (loop=loop@entry=0x7fae55bfe890, 
    ms=ms@entry=-1) at /usr/src/debug/neovim-0.2.2/src/nvim/event/loop.c:52
#5  0x00000000005cdb60 in tui_main (bridge=0x7fae55ca4c00, ui=0x7fae5c8f8c00)
    at /usr/src/debug/neovim-0.2.2/src/nvim/tui/tui.c:343
#6  0x00000000005d0587 in ui_thread_run (data=<optimized out>)
    at /usr/src/debug/neovim-0.2.2/src/nvim/ui_bridge.c:104
#7  0x00007fae5ece5dd5 in start_thread (arg=0x7fae55bff700) at pthread_create.c:308
#8  0x00007fae5d459b3d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 1 (Thread 0x7fae5f514780 (LWP 6746)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007fae5f11ee1a in uv__epoll_wait (epfd=<optimized out>, 
    events=events@entry=0x7ffec32bd280, nevents=nevents@entry=1024, 
    timeout=timeout@entry=-1) at src/unix/linux-syscalls.c:321
#2  0x00007fae5f11d14f in uv__io_poll (loop=loop@entry=0x8a0ca0 <main_loop>, timeout=-1)
    at src/unix/linux-core.c:271
#3  0x00007fae5f10edb8 in uv_run (loop=loop@entry=0x8a0ca0 <main_loop>, mode=UV_RUN_ONCE)
    at src/unix/core.c:352
#4  0x00000000004a0827 in loop_poll_events (loop=0x8a0ca0 <main_loop>, ms=ms@entry=-1)
    at /usr/src/debug/neovim-0.2.2/src/nvim/event/loop.c:52
#5  0x0000000000523f32 in channel_send_call (id=<optimized out>, 
    method_name=0x7fae55cc96a0 "/home/matej/.vim/pack/thirdparty/start/nvimfs/rplugin/python3/nvimfs:autocmd:VimEnter:*", args=..., err=err@entry=0x7ffec32c0490)
    at /usr/src/debug/neovim-0.2.2/src/nvim/msgpack_rpc/channel.c:242
#6  0x000000000047b5b2 in f_rpcrequest (argvars=0x7ffec32c0790, rettv=0x7ffec32c1270, 
    fptr=<optimized out>) at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:13909
#7  0x000000000048223b in call_func (funcname=funcname@entry=0x7fae55d75a80 "rpcrequest", 
    len=<optimized out>, rettv=rettv@entry=0x7ffec32c1270, 
    argcount_in=argcount_in@entry=2, argvars_in=argvars_in@entry=0x7ffec32c0790, 
    argv_func=argv_func@entry=0x0, firstline=1, lastline=1, 
    doesrange=doesrange@entry=0x7ffec32c078c, evaluate=evaluate@entry=true, 
    partial=partial@entry=0x0, selfdict_in=selfdict_in@entry=0x0)
    at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:6408
#8  0x0000000000482e4a in func_call (name=<optimized out>, 
    args=args@entry=0x7ffec32c0bf0, partial=partial@entry=0x0, selfdict=0x0, 
    rettv=rettv@entry=0x7ffec32c1270) at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:7313
#9  0x0000000000482f51 in f_call (argvars=0x7ffec32c0be0, rettv=0x7ffec32c1270, 
    fptr=<optimized out>) at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:7360
#10 0x000000000048223b in call_func (funcname=funcname@entry=0x7fae55ca3d88 "call", 
    len=len@entry=4, rettv=rettv@entry=0x7ffec32c1270, argcount_in=argcount_in@entry=2, 
    argvars_in=argvars_in@entry=0x7ffec32c0be0, argv_func=argv_func@entry=0x0, 
---Type <return> to continue, or q <return> to quit---
    firstline=firstline@entry=1, lastline=lastline@entry=1, 
    doesrange=doesrange@entry=0x7ffec32c0dbc, evaluate=evaluate@entry=true, 
    partial=partial@entry=0x0, selfdict_in=selfdict_in@entry=0x0)
    at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:6408
#11 0x000000000048626b in get_func_tv (name=name@entry=0x7fae55ca3d88 "call", len=4, 
    rettv=rettv@entry=0x7ffec32c1270, arg=arg@entry=0x7ffec32c1220, firstline=1, 
    lastline=1, doesrange=doesrange@entry=0x7ffec32c0dbc, evaluate=evaluate@entry=1, 
    partial=0x0, selfdict=selfdict@entry=0x0)
    at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:6148
#12 0x00000000004846b5 in eval7 (arg=arg@entry=0x7ffec32c1220, 
    rettv=rettv@entry=0x7ffec32c1270, evaluate=evaluate@entry=1, 
    want_string=want_string@entry=0) at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:4248
#13 0x000000000048490a in eval6 (arg=arg@entry=0x7ffec32c1220, 
    rettv=rettv@entry=0x7ffec32c1270, evaluate=evaluate@entry=1, 
    want_string=want_string@entry=0) at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:3945
#14 0x0000000000484c05 in eval5 (arg=arg@entry=0x7ffec32c1220, 
    rettv=rettv@entry=0x7ffec32c1270, evaluate=evaluate@entry=1)
    at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:3796
#15 0x0000000000484f40 in eval4 (arg=arg@entry=0x7ffec32c1220, 
    rettv=rettv@entry=0x7ffec32c1270, evaluate=evaluate@entry=1)
    at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:3533
#16 0x0000000000485801 in eval3 (arg=arg@entry=0x7ffec32c1220, 
    rettv=rettv@entry=0x7ffec32c1270, evaluate=evaluate@entry=1)
    at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:3451
#17 0x000000000048593f in eval2 (arg=arg@entry=0x7ffec32c1220, 
    rettv=rettv@entry=0x7ffec32c1270, evaluate=evaluate@entry=1)
    at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:3382
#18 0x0000000000485a7e in eval1 (arg=arg@entry=0x7ffec32c1220, 
    rettv=rettv@entry=0x7ffec32c1270, evaluate=evaluate@entry=1)
    at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:3309
#19 0x00000000004871b3 in eval0 (arg=0x7fae5cbdc0dc "call('rpcrequest', [a:chan]+a:000)", 
    rettv=rettv@entry=0x7ffec32c1270, nextcmd=nextcmd@entry=0x7ffec32c1318, evaluate=1)
    at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:3269
#20 0x000000000048d113 in ex_let (eap=0x7ffec32c1310)
    at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:1499
#21 0x00000000004bfc8e in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffec32c1540, 
    flags=flags@entry=7, cstack=cstack@entry=0x7ffec32c15d0, 
    fgetline=fgetline@entry=0x4837e5 <get_func_line>, cookie=cookie@entry=0x7fae5c898000)
    at /usr/src/debug/neovim-0.2.2/src/nvim/ex_docmd.c:2242
#22 0x00000000004c0656 in do_cmdline (cmdline=<optimized out>, cmdline@entry=0x0, 
    fgetline=fgetline@entry=0x4837e5 <get_func_line>, cookie=cookie@entry=0x7fae5c898000, 
    flags=flags@entry=7) at /usr/src/debug/neovim-0.2.2/src/nvim/ex_docmd.c:609
#23 0x0000000000481aaa in call_user_func (fp=fp@entry=0x7fae5c83cf60, 
    argcount=argcount@entry=2, argvars=argvars@entry=0x7ffec32c20a0, 
    rettv=rettv@entry=0x7ffec32c2280, firstline=firstline@entry=1, 
    lastline=lastline@entry=1, selfdict=0x0)
    at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:21408
#24 0x00000000004821dd in call_func (
    funcname=funcname@entry=0x7fae55cdfc00 "remote#define#request", len=len@entry=21, 
    rettv=rettv@entry=0x7ffec32c2280, argcount_in=argcount_in@entry=2, 
    argvars_in=argvars_in@entry=0x7ffec32c20a0, argv_func=argv_func@entry=0x0, 
---Type <return> to continue, or q <return> to quit---
    firstline=firstline@entry=1, lastline=lastline@entry=1, 
    doesrange=doesrange@entry=0x7ffec32c226c, evaluate=evaluate@entry=true, 
    partial=partial@entry=0x0, selfdict_in=selfdict_in@entry=0x0)
    at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:6393
#25 0x000000000048626b in get_func_tv (
    name=name@entry=0x7fae55cdfc00 "remote#define#request", len=21, 
    rettv=rettv@entry=0x7ffec32c2280, arg=arg@entry=0x7ffec32c2270, firstline=1, 
    lastline=1, doesrange=doesrange@entry=0x7ffec32c226c, evaluate=1, partial=0x0, 
    selfdict=0x0) at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:6148
#26 0x000000000048b450 in ex_call (eap=0x7ffec32c2350)
    at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:2760
#27 0x00000000004bfc8e in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffec32c2580, 
    flags=flags@entry=7, cstack=cstack@entry=0x7ffec32c2610, 
    fgetline=fgetline@entry=0x4d5c19 <getnextac>, cookie=cookie@entry=0x7ffec32c2bc0)
    at /usr/src/debug/neovim-0.2.2/src/nvim/ex_docmd.c:2242
#28 0x00000000004c0656 in do_cmdline (cmdline=<optimized out>, cmdline@entry=0x0, 
    fgetline=fgetline@entry=0x4d5c19 <getnextac>, cookie=cookie@entry=0x7ffec32c2bc0, 
    flags=flags@entry=7) at /usr/src/debug/neovim-0.2.2/src/nvim/ex_docmd.c:609
#29 0x00000000004d6f5d in apply_autocmds_group (event=EVENT_VIMENTER, 
    fname=0x7fae5caabb20 "", fname@entry=0x7fae5cbdc1e8 "", fname_io=fname_io@entry=0x0, 
    force=force@entry=true, group=group@entry=14, buf=buf@entry=0x7fae5c858000, 
    eap=eap@entry=0x0) at /usr/src/debug/neovim-0.2.2/src/nvim/fileio.c:6896
#30 0x00000000004d74df in do_doautocmd (arg=0x7fae5cbdc1e8 "", do_msg=do_msg@entry=1, 
    did_something=did_something@entry=0x7ffec32c2caf)
    at /usr/src/debug/neovim-0.2.2/src/nvim/fileio.c:6273
#31 0x00000000004b724c in ex_doautocmd (eap=<optimized out>)
    at /usr/src/debug/neovim-0.2.2/src/nvim/ex_docmd.c:4560
#32 0x00000000004bfc8e in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffec32c2f60, 
    flags=flags@entry=3, cstack=cstack@entry=0x7ffec32c2ff0, 
    fgetline=fgetline@entry=0x4837e5 <get_func_line>, cookie=cookie@entry=0x7fae5c894000)
    at /usr/src/debug/neovim-0.2.2/src/nvim/ex_docmd.c:2242
#33 0x00000000004c0656 in do_cmdline (cmdline=<optimized out>, 
    fgetline=0x4837e5 <get_func_line>, cookie=0x7fae5c894000, flags=flags@entry=3)
    at /usr/src/debug/neovim-0.2.2/src/nvim/ex_docmd.c:609
#34 0x0000000000489526 in ex_execute (eap=0x7ffec32c3610)
    at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:19573
#35 0x00000000004bfc8e in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffec32c3840, 
    flags=flags@entry=7, cstack=cstack@entry=0x7ffec32c38d0, 
    fgetline=fgetline@entry=0x4837e5 <get_func_line>, cookie=cookie@entry=0x7fae5c894000)
    at /usr/src/debug/neovim-0.2.2/src/nvim/ex_docmd.c:2242
#36 0x00000000004c0656 in do_cmdline (cmdline=<optimized out>, cmdline@entry=0x0, 
    fgetline=fgetline@entry=0x4837e5 <get_func_line>, cookie=cookie@entry=0x7fae5c894000, 
    flags=flags@entry=7) at /usr/src/debug/neovim-0.2.2/src/nvim/ex_docmd.c:609
#37 0x0000000000481aaa in call_user_func (fp=fp@entry=0x7fae5c83c940, 
    argcount=argcount@entry=6, argvars=argvars@entry=0x7ffec32c43a0, 
    rettv=rettv@entry=0x7ffec32c4580, firstline=firstline@entry=1, 
    lastline=lastline@entry=1, selfdict=0x0)
    at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:21408
#38 0x00000000004821dd in call_func (
    funcname=funcname@entry=0x7fae55cdfb20 "remote#define#AutocmdBootstrap", 
    len=len@entry=30, rettv=rettv@entry=0x7ffec32c4580, argcount_in=argcount_in@entry=6, 
---Type <return> to continue, or q <return> to quit---
    argvars_in=argvars_in@entry=0x7ffec32c43a0, argv_func=argv_func@entry=0x0, 
    firstline=firstline@entry=1, lastline=lastline@entry=1, 
    doesrange=doesrange@entry=0x7ffec32c456c, evaluate=evaluate@entry=true, 
    partial=partial@entry=0x0, selfdict_in=selfdict_in@entry=0x0)
    at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:6393
#39 0x000000000048626b in get_func_tv (
    name=name@entry=0x7fae55cdfb20 "remote#define#AutocmdBootstrap", len=30, 
    rettv=rettv@entry=0x7ffec32c4580, arg=arg@entry=0x7ffec32c4570, firstline=1, 
    lastline=1, doesrange=doesrange@entry=0x7ffec32c456c, evaluate=1, partial=0x0, 
    selfdict=0x0) at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:6148
#40 0x000000000048b450 in ex_call (eap=0x7ffec32c4650)
    at /usr/src/debug/neovim-0.2.2/src/nvim/eval.c:2760
#41 0x00000000004bfc8e in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffec32c4880, 
    flags=flags@entry=7, cstack=cstack@entry=0x7ffec32c4910, 
    fgetline=fgetline@entry=0x4d5c19 <getnextac>, cookie=cookie@entry=0x7ffec32c4ec0)
    at /usr/src/debug/neovim-0.2.2/src/nvim/ex_docmd.c:2242
#42 0x00000000004c0656 in do_cmdline (cmdline=<optimized out>, cmdline@entry=0x0, 
    fgetline=fgetline@entry=0x4d5c19 <getnextac>, cookie=cookie@entry=0x7ffec32c4ec0, 
    flags=flags@entry=7) at /usr/src/debug/neovim-0.2.2/src/nvim/ex_docmd.c:609
#43 0x00000000004d6f5d in apply_autocmds_group (event=event@entry=EVENT_VIMENTER, 
    fname=0x7fae55ca3188 "", fname@entry=0x0, fname_io=fname_io@entry=0x0, 
    force=force@entry=false, group=group@entry=-3, buf=0x7fae5c858000, eap=eap@entry=0x0)
    at /usr/src/debug/neovim-0.2.2/src/nvim/fileio.c:6896
#44 0x00000000004d75b6 in apply_autocmds (event=event@entry=EVENT_VIMENTER, 
    fname=fname@entry=0x0, fname_io=fname_io@entry=0x0, force=force@entry=false, 
    buf=<optimized out>) at /usr/src/debug/neovim-0.2.2/src/nvim/fileio.c:6541
#45 0x00000000005026c2 in main (argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/neovim-0.2.2/src/nvim/main.c:536
(gdb)
```

**Comment by mcepl** [comment]
```
Chyba při zpracování function remote#define#request:
řádek    2:
Error invoking '/home/matej/.vim/pack/modules/start/nvimfs/rplugin/python3/nvimfs:autocmd:VimEnter:*' on channel 4 (python3-rplugin-host):
error caught in request handler '/home/matej/.vim/pack/modules/start/nvimfs/rplugin/python3/nvimfs:autocmd:VimEnter:* []':
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matej/.vim/pack/modules/start/nvimfs/rplugin/python3/nvimfs/__init__.py", line 40, in init
    self.spawn_neovimfs()
  File "/home/matej/.vim/pack/modules/start/nvimfs/rplugin/python3/nvimfs/__init__.py", line 59, in spawn_neovimfs
    newf.write(start_addr)
FileNotFoundError: [Errno 2] No such file or directory
Press ENTER or type command to continue
```
